kernel:
    resource: ../../src/Kernel.php
    type: annotation

user_controllers:
    resource: ../../src/User/Controller/
    type: annotation
    prefix: /api/users
    trailing_slash_on_root: false

reservation_controllers:
    resource: ../../src/Reservation/Adapter/Framework/Http/Controller/Reservation/
    type: annotation
    prefix: /api/reservations
    trailing_slash_on_root: false

workstation_controllers:
    resource: ../../src/Reservation/Adapter/Framework/Http/Controller/Workstation/
    type: annotation
    prefix: /api/workstations
    trailing_slash_on_root: false


