user_controllers:
    resource: ../../src/User/Controller/
    type: annotation
    prefix: /api/users
    trailing_slash_on_root: false

workstation_controllers:
    resource: ../../src/Workstation/Adapter/Framework/Http/Controller/
    type: annotation
    prefix: /api/workstations
    trailing_slash_on_root: false

kernel:
    resource: ../../src/Kernel.php
    type: annotation
