user_controllers:
    resource: ../../src/User/Controller/
    type: annotation
    prefix: /api/users
    trailing_slash_on_root: false

workstation_controllers:
    resource: ../../src/Workstation/Controller/
    type: annotation
    prefix: /api/module-a
    trailing_slash_on_root: false

kernel:
    resource: ../../src/Kernel.php
    type: annotation
